apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ahlemman26125831/backend-projectflow:latest
        ports:
        - containerPort: 5000
        env:
          # On utilise secretKeyRef au lieu de configMapKeyRef
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: projectflow-secrets
                key: MONGO_URI
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: projectflow-secrets
                key: GEMINI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002