apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ahlemman26125831/frontend-projectflow:latest # Image publiée sur Docker Hub
        ports:
        - containerPort: 80
        env: # Section ajoutée pour la communication
          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                name: projectflow-config
                key: REACT_APP_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 # Port utilisé pour l'accès navigateur
  type: NodePort